### ISSUE TITLE
no puedo crear fork

### ISSUE THREAD

**Issue by cezhar** [concretesolutions/desafio-android#25]
Tengo listo el desafío, no obstante cuando creo el fork me manda a una página con error 404
<img width="1158" alt="captura de pantalla 2018-10-21 a la s 23 40 18" src="https://user-images.githubusercontent.com/19785528/47276027-b1345480-d58a-11e8-85d2-93ee725098f0.png">

dejo el link del proyecto en drive: https://drive.google.com/open?id=1BzLxex2uHMgdpVgX3eLhKMaOMNeJlhGP

**Comment by cs-davi-silva** [comment]
Yo creo que es algún problema en el github.
¿Puede intentar nuevamente?

Gracias!

**Comment by cezhar** [comment]
Hola:

Efectivamente era un problema en Github, logré subir mis archivos recién hoy por la mañana.

Saludos cordiales
